site_name: Cuddly Funicular
site_url: https://ktdtkpohhdj.github.io/cuddly-funicular/
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - docs/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

