site_name: Cuddly Funicular
site_url: https://ktdtkpohhdj.github.io/cuddly-funicular/
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["src"]
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py

  

