site_name: Cuddly Funicular
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["cuddy-funicular/src"]
  - gen-files
  
hooks:
  - docs/gen_ref_pages.py

  

