name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - site

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings[python] mkdocs-gen-files pyyaml
          
      - name: Checkout plugins from config
        env:
            GH_PAT: ${{ secrets.PL_TOKEN }}
        run: |
            python <<EOF
            import yaml
            import os

            token = os.environ["GH_PAT"]

            with open("plugins.yml") as f:
            config = yaml.safe_load(f)

            for plugin in config["plugins"]:
                name = plugin["name"]
                repo = plugin["repo"]

                cmd = (
                  f'git -c http.extraheader="AUTHORIZATION: bearer {token}" '
                  f'clone https://github.com/{repo}.git plugins/{name}'
                )

            os.system(cmd)
            EOF

          
      - name: Add plugins to PYTHONPATH
        run: |
          for dir in plugins/*; do
           echo "PYTHONPATH=$PYTHONPATH:$(pwd)/$dir/src" >> $GITHUB_ENV
           done

      - name: Generate plugin docs
        run: python docs/generate_plugin_docs.py    

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
