name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - site

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings[python]
          
      - name: Checkout private docs
        uses: actions/checkout@v4
        with:
          repository: ktdtpohhdj/cuddly_funicular_privat
          token: ${{ secrets.PL_TOKEN }}
          ref: docs-dist
          path: docs/private

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
