name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - site

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material mkdocstrings[python]
          
      - name: Download private docs
        uses: dawidd6/action-download-artifact@v3
        with:
          github_token: ${{ secrets.PLUGIN_DOCS_TOKEN }}
          repo: ktdtpohhdj/cuddly_funicular_privat
          workflow: Build private documentation
          workflow_search: true
          workflow_conclusion: success
          name: private-docs
          path: docs/private


      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
